version: "3"

services:

    # A PostgreSQL instance containing schemas from CDMSs that use PostgreSQL (currently clide and wmdr)
    postgresql:
        image: postgres
        container_name: test-postgresql
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=password


    # A MariaDB instance containing schemas from CDMSs that use MySQL/MariaDB (currently climsoft-4.1.1 and mch-english)
    mysql:
        image: mysql
        container_name: test-mysql
        command: --default-authentication-plugin=mysql_native_password --collation_server=utf8_general_ci --character_set_server=utf8
        volumes:
            - ./docker/disable-strict-mode.cnf:/etc/mysql/conf.d/disable_strict_mode.cnf
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=test
